language: java
git:
  depth: false
jdk:
  - oraclejdk8
dist: trusty
cache:
  directories:
    - $HOME/.m2
notifications:
  email:
    -tony.seguin9@gmail.com
  on_success: never 
  on_failure: always
addons:
  sonarcloud:
    organization: "tonyseg-github

